### ISSUE TITLE
运行occluded_reid中的infer.py时报错

### ISSUE THREAD

**Issue by X-ray0214** [wangguanan/light-reid#38]
expect a head in dict_keys(['bnhead', 'BNHead', 'CodePyramid', 'BottleClassifier']) but got SkeletonMultiHeads，请问如何解决？

**Comment by wangguanan** [comment]
代码中你直接注释掉这一行不影响运行后面不会修复这个bug
             
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
Guan'an WangInstitute of Automation, Chinese Academy of Sciences,No. 95 Zhongguancun East Rd., Beijing, China.

---- 回复的原邮件 ***@***.***>发送日期2021年07月19日 11:29 ***@***.***> ***@***.***>主题[wangguanan/light-reid] 运行occluded_reid中的infer.py时报错 (#38)

expect a head in dict_keys(['bnhead', 'BNHead', 'CodePyramid', 'BottleClassifier']) but got SkeletonMultiHeads，请问如何解决？



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/wangguanan/light-reid/issues/38",

"url": "https://github.com/wangguanan/light-reid/issues/38",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by xddlj** [comment]
return __head_factory[name](in_dim=in_dim, class_num=class_num, classifier=classifier, **kwargs)
KeyError: 'SkeletonMultiHeads'

**Comment by wangguanan** [comment]
下周我看看

**Comment by wangguanan** [comment]
请参考这个commit：https://github.com/wangguanan/light-reid/commit/490089a6438b0bcc90d4e4d3fc5d2a440bd9e8e0#diff-6b93d3fb17ab0dadfc8b184c548a6b7e6c94542c4bb0147477b5e0638f658187R15
